<a href="https://colab.research.google.com/github/goyaldimpi/BasicMachineLearning/blob/master/iris_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from sklearn import datasets
from sklearn import svm
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split

# Loading Datasets

In [0]:
iris = datasets.load_iris()

In [139]:
type(iris)

sklearn.utils.Bunch

In [140]:
iris.data         #this shows the data inside the iris

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [141]:
iris.feature_names    # this tells the feature name of iris

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [142]:
iris.target  #this represent the value of various class labels

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [143]:
iris.target_names   #this shows the class label name 

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [0]:
X = iris.data
Y = iris.target

In [145]:
print(X)
print(Y)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [146]:
type(X)
type(Y)

numpy.ndarray

In [0]:
data = pd.DataFrame(X, columns = iris.feature_names)

In [0]:
X_train, X_test,Y_train,Y_test = train_test_split(X, Y, test_size=0.2 ,stratify =Y, random_state = 2)

In [149]:
type(X_train)

numpy.ndarray

In [150]:
data.describe()

sepal length (cm)  sepal width (cm)  petal length (cm)  \
count         150.000000        150.000000         150.000000   
mean            5.843333          3.057333           3.758000   
std             0.828066          0.435866           1.765298   
min             4.300000          2.000000           1.000000   
25%             5.100000          2.800000           1.600000   
50%             5.800000          3.000000           4.350000   
75%             6.400000          3.300000           5.100000   
max             7.900000          4.400000           6.900000   

       petal width (cm)  
count        150.000000  
mean           1.199333  
std            0.762238  
min            0.100000  
25%            0.300000  
50%            1.300000  
75%            1.800000  
max            2.500000

In [151]:
X_train


array([[6.1, 2.9, 4.7, 1.4],
       [6.3, 2.7, 4.9, 1.8],
       [6.3, 3.3, 6. , 2.5],
       [5.9, 3. , 5.1, 1.8],
       [4.9, 3.1, 1.5, 0.1],
       [5.9, 3. , 4.2, 1.5],
       [5.6, 3. , 4.5, 1.5],
       [6.7, 2.5, 5.8, 1.8],
       [6. , 2.9, 4.5, 1.5],
       [5.5, 2.5, 4. , 1.3],
       [6.3, 2.5, 5. , 1.9],
       [6. , 2.2, 4. , 1. ],
       [6.3, 2.3, 4.4, 1.3],
       [5.5, 2.3, 4. , 1.3],
       [6.4, 2.8, 5.6, 2.2],
       [5.5, 2.4, 3.7, 1. ],
       [6.3, 2.9, 5.6, 1.8],
       [6.8, 3.2, 5.9, 2.3],
       [4.8, 3.4, 1.9, 0.2],
       [7.7, 3. , 6.1, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [6.1, 2.6, 5.6, 1.4],
       [6.2, 2.9, 4.3, 1.3],
       [4.8, 3. , 1.4, 0.1],
       [6.8, 3. , 5.5, 2.1],
       [6.4, 2.8, 5.6, 2.1],
       [4.4, 3. , 1.3, 0.2],
       [6.7, 3.1, 4.7, 1.5],
       [6.7, 3.1, 5.6, 2.4],
       [5. , 3.6, 1.4, 0.2],
       [6. , 2.7, 5.1, 1.6],
       [6.7, 3.3, 5.7, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [4.3, 3. , 1.1, 0.1],
       [5.6, 2

In [0]:
X_test

In [0]:
Y_train

In [154]:
Y_test

array([0, 2, 2, 0, 1, 2, 2, 2, 0, 0, 1, 1, 1, 2, 0, 2, 1, 0, 2, 0, 1, 1,
       0, 1, 1, 2, 2, 0, 1, 0])

In [0]:
data['class'] = Y

In [0]:
plt.plot(X_train,'*')
plt.show()

In [0]:
plt.plot(X_test,'*')
plt.show()

In [0]:
plt.plot(Y_train,'*')
plt.show()

In [0]:
plt.plot(Y_test,'*')
plt.show()

In [0]:
data.groupby('class').mean()

In [0]:
data['class'].value_counts()

In [0]:
data['class'].min()

In [0]:
data['class'].max()

In [164]:
print(iris.target.min(),iris.data.min())

0 0.1


In [169]:
model = svm.SVC(kernel ='linear')
model.fit(X_train,Y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)

In [0]:
Y_pred_mod = model.predict(X_test)

In [0]:
from sklearn.metrics import accuracy_score

In [176]:
print(accuracy_score(Y_test,Y_pred_mod))



0.9666666666666667


In [174]:
model.fit(X_test,Y_test)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto_deprecated',
  kernel='linear', max_iter=-1, probability=False, random_state=None,
  shrinking=True, tol=0.001, verbose=False)